### ISSUE TITLE
Improve size

### ISSUE THREAD

**Issue by HugoGiraudel** [gillesbertaux/andy#28]
Current:

```scss
/// Sizing helper
/// @access public
/// @param {Length} $width - Width
/// @param {Length} $height - Height
/// @example scss - Usage
///   .foo {
///     @include size(350px, 350px);
///   }
/// @example css - Result
///   .foo {
///     width: 350px;
///     height: 350px;
///   }
@mixin size($width, $height) {
    width: $width;
    height: $height;
}
```

Suggested:

```scss
/// Sizing helper
/// @access public
/// @param {Length} $width - Width
/// @param {Length} $height - Height
/// @example scss - Usage
///   .foo {
///     @include size(350px);
///   }
/// @example css - Result
///   .foo {
///     width: 350px;
///     height: 350px;
///   }
@mixin size($width, $height: $width) {
    width: $width;
    height: $height;
}
```
