### ISSUE TITLE
What is the point of `border`

### ISSUE THREAD

**Issue by HugoGiraudel** [gillesbertaux/andy#8]
I don't see the point. Did I miss something?

```scss
@mixin border($thickness, $type, $color) { border: $thickness $type $color; }
```

https://github.com/gillesbertaux/andy/blob/master/andy.scss#L100
